name: Publish Package
on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Set up Git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "9cats+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Install Dependencies
      run: yarn
    - name: Build and Publish NPM Module
      run: |
        mkdir -p ci
        cp package.json README.md ci/
        npm install --prefix ci
        node ci/build.js
      env:
        NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
